### ISSUE TITLE
Resource Description - Remove Choose a License Field Replace with Terms of Use

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/avalon#98]
### Descriptive summary

Based on discussions about the use of license vs. terms of use:

1. Remove choose a license field
1. Replace with terms of use (in same place, after publication date), and map to access condition element. Make terms of use a required field 
1. Create standard (CC, etc.) license text helper drop-down. User selects standard license and text is populated into field or they can enter custom license text

### Related work
#58 #73 to fit with this decision

**Comment by cwant** [comment]
Here is where I am currently going with the UX, so it's probably worth a sanity check:

![terms_of_use](https://user-images.githubusercontent.com/672104/27140882-e4cc3722-50e3-11e7-85bc-eec3ea5d9b4f.png)

Workflow:
  a) user either writes own text into the text area, and/or;
  b) user selects one (or more) licenses from the pull down;
  c) the 'append' button injects the license text at the end of whatever is in the text area (as opposed to clobbering the text that is already there).

I thought it might be a good idea to include the button that actually injects the text into the field. Having just a pull down trigger the injection of the license text might cause some issues where the user ends up accidentally injecting a bunch of licenses into the text area. On the down side, the user might just select a license and not press the button, which could cause some confusion.

**Comment by seanluyk** [comment]
This approach looks good to me, @cwant. I wonder if there's a way to make the append license text button more prominent (placement, text) somehow? I could imagine a scenario where a user selects a license but forgets to click append, and may be confused by why they get an error message. Otherwise, I agree that the button is probably the best option for the reasons you mention

**Comment by cwant** [comment]
I'm playing with making the append button flash green a couple of times after a license is selected (as a hint that they should hit the button). Might be enough of a hint, hopefully I can demo it soon.

One issue that I'm having now is that I am unable to find text for the Public Domain Mark 1.0 license. For the other license types I can find "legal code" resources like this one:

https://creativecommons.org/licenses/by-nc/4.0/legalcode.txt

But for Public Domain Mark 1.0, the best I can find is a "deed" style license page:

https://creativecommons.org/publicdomain/mark/1.0/

I'm not sure if I should just copy/paste the text from the deed into the application.

**Comment by seanluyk** [comment]
Are you referring to the text that gets injected when a user selects a license @cwant? I'm not sure where the existing text that appears when you select a license came from, but it should be OK for our purposes (as opposed to needing to add the full license text, although a link to the licenses would be helpful for users)

**Comment by cwant** [comment]
Hi @seanluyk,

I'm not sure the current license descriptions work well within the context of a user looking at a record after it has been deposited into Avalon (they are more tailored to the depositor, as guidance as to when the license is applicable). In our current application we don't store these descriptions within the metadata anywhere (we store the license name instead, coming from the controlled vocabulary).

This is what we have for the descriptions currently:

```yaml
  Attribution_4.0_International: With this license you allow others to "distribute, remix, tweak, and build" on your deposited content, including for commercial uses, provided they attribute you as the original creator.
  Attribution-ShareAlike_4.0_International: With this license you allow others to "remix, tweak, and build" on your deposited content, including for commercial uses, provided they attribute you as the original creator AND incorporate the same level of licensing for the newly resulting creation. "All new works based on yours will carry the same license, so any derivatives will also allow commercial use."
  Attribution-NonCommercial_4.0_International: With this license you allow others to "remix, tweak, and build" on your content in non-commercial ways. While they must credit you as the original creator and while the remixed, tweaked, or expanded upon content must remain non-commercial, they do not have to apply identical license terms on the new content.
  Attribution-NoDerivs_4.0_International: With this license you share your work with others and allow them to download your work, provided they attribute you as the creator and refrain from changing the content in any way.
  Attribution-NonCommercial-NoDerivs_4.0_International: With this license you share your work with others and allow them to download your work, provided they attribute you as the creator and refrain from changing the content in any way, including for commercial means.
  Attribution-NonCommercial-ShareAlike_4.0_International: With this license you allow others to "remix, tweak, and build" on your content in non-commercial ways, provided they attribute you as the original creator AND incorporate the same level of licensing for the newly resulting creation. "All new works based on yours will carry the same license, so any derivatives will also allow commercial use."
  Public_Domain_Mark_1.0: When content is in the public domain, it has no known copyright owner.
  CC0_1.0_Universal: With this license you are waiving your rights as copyright owner to the content you upload. This means your content may be distributed and reused without attribution, without restriction. CC0 is a license that one applies to one's own work; rarely does one apply it to another's work, unless one has the appropriate rights to do so.
```

When a user looks at the metadata for a deposited record later, I'm not sure this is the sort of thing that they want to read (they may not want to read the entire license either). So at the very least, some of this text needs to be reworked.

(A ping to @weiweishi and @sfarnel in case they have opinions.)
